domain: cesar-florian.github.io
url: https://cesar-florian.github.io
baseurl: /  #/portfolio

# Site settings
title: César Florian
logo-text: CF
email: ce.florian.27@gmail.com
description: 'Soy un profesional especializado en el diseño y la implementación de soluciones de software eficientes, escalables y alineadas a las necesidades estratégicas de las empresas. Mi trabajo se centra en construir arquitecturas de microservicios en entornos cloud usando .NET para resolver desafíos complejos de manera eficiente.'
summary: 'Tengo más de [year] años de experiencia diseñando, desarrollando e implementando soluciones distribuidas escalables. Destaco en arquitecturas orientadas a eventos, microservicios y APIs RESTful, pero también en la optimización de sistemas existentes, modernización de aplicaciones heredadas y adopción de buenas prácticas de desarrollo seguro. He liderado iniciativas de integración con múltiples plataformas, aplicado patrones de diseño para mejorar la resiliencia de los sistemas y trabajado en la implementación de prácticas de observabilidad para garantizar disponibilidad y rendimiento. Mi enfoque une la parte técnica con las necesidades del negocio, garantizando que cada solución realmente resuelva problemas y genere valor para la organización.'
start-year: 2020
image: img/about/me.jpg

# Universidades/instituciones, nombre y titulo/certificado
university:

- name: Universidad Mariano Gálvez
  pic: umg.png
  degree: Maestría en Seguridad Informática
  year: 2023
  url: https://www.umg.edu.gt

- name: Universidad Mariano Gálvez
  pic: umg.png
  degree: Ingeniería en Sistemas de Información y Ciencias de la Computación
  year: 2017
  url: https://www.umg.edu.gt

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:

  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

experience:

- institution: Banco Promerica
  position: Analista Programador .NET
  url: https://www.bancopromerica.com.gt
  pic: promerica.svg
  period: julio 2024 - presente
  country: Guatemala
  details: 
  - line: Modelado y documentación de sistemas utilizando UML y herramientas de diseño.
  - line: Mantenimiento de aplicaciones y servicios web de sistemas financieros.
  - line: Pruebas funcionales de sistemas.

- institution: AirPak
  position: Ingeniero de Software
  url: https://airpak.com.ni
  pic: airpak.jpg
  period: junio 2021 - julio 2024
  country: Nicaragua
  details: 
  - line: Mantenimiento de aplicaciones y servicios web de sistemas transaccionales de remesas.
  - line: Integración de pasarela de pagos con el backend del sistema.
  - line: Implementación de herramienta de análisis de comportamiento de usuarios en aplicaciones web construidas en React.
  - line: Integración de proveedor externo para el envío de SMS.
  - line: Responsable de liderar la integración de servicio de verificación de identidad a través de servicios web de terceros.
  - line: Implementación e integración de servicios de colectores de pagos de servicios en sistema basado en las tecnologías .NET y React.

- institution: IT Profis
  position: Desarrollador de Software
  url: https://www.itprofis-gt.com
  pic: itprofis.svg
  period: abril 2020 - julio 2024
  country: Guatemala
  details: 
  - line: Migración y reestructuración de sistema de créditos hacia una arquitectura basada en microservicios.
  - line: Implementación de seguridad basada en tokens utilizando OAuth2 y JWT.
  - line: Desarrollo e integración de servicios de procesamiento de transacciones (colectores) para entidades internacionales.


services:

- title: Arquitectura de software y soluciones empresariales
  description: Diseño de sistemas escalables, modulares y seguros, alineados con las necesidades estratégicas de la organización.
  icon: fa-sitemap

- title: Desarrollo de software personalizado
  description: Construcción de aplicaciones a medida (web, APIs y sistemas distribuidos) utilizando .NET y tecnologías modernas, con foco en rendimiento y mantenibilidad.
  icon: fa-code

- title: Soluciones empresariales en la nube
  description: Diseño y despliegue de aplicaciones en entornos cloud (Oracle Cloud, GCP, Azure), aplicando buenas prácticas de escalabilidad, seguridad y optimización de costos.
  icon: fa-cloud

- title: Seguridad de la información
  description: 'Integración de estándares de seguridad en el ciclo de vida del software: protección de datos sensibles, controles de acceso, auditoría y cumplimiento normativo.'
  icon: fa-shield

- title: Pruebas, observabilidad y garantía de calidad
  description: Implementación de pruebas automatizadas y monitoreo de métricas, logs y trazas para asegurar aplicaciones confiables, estables y fáciles de mantener.
  icon: fa-check-square-o

- title: Integración de sistemas y APIs
  description: Conexión de aplicaciones internas, plataformas externas y servicios en la nube, garantizando interoperabilidad, seguridad y confiabilidad.
  icon: fa-plug


skills:

- group: Cloud, DevOps y control de versiones
  list: [ Oracle Cloud / OCI, Docker, Kubernetes, GCP, IIS, Linux, Git / GitHub, Azure / AKS ]

- group: Desarrollo (Backend y Frontend)
  list: [ C# / .NET, SQL Server, Entity Framework, RabbitMQ, SOAP / REST, MongoDB, JavaScript, JQuery, React, Bootstrap, HTML / CSS, Python ]

- group: Arquitectura y diseño
  list: [ Clean Architecture, Microservices, High Availability, PlantUML, YARP / API Gateway, MVC, Design Patterns, Event-Driven Architecture, Hexagonal Architecture, Domain Driven Design, CQRS, Event Sourcing, Pub-Sub Pattern, Saga Patterns, SNS / SQS, Backend For Frontend, BIAN / Open Banking ]

- group: Calidad y observabilidad
  list: [ Testing, Dynatrace, Grafana, Prometheus, Jaeger, OpenTelemetry, Logging, Kibana ]

- group: Seguridad
  list: [ JWT, OAuth2, RSA / Cryptography, OWASP ]



# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty