url: https://cesar-florian.github.io
baseurl: /portfolio

# Site settings
title: César Florian
email: ce.florian.27@gmail.com
description: "Experto en el diseño y la implementación de soluciones de software. Mi trabajo se centra en construir arquitectura de microservicios en entornos cloud usando .NET para resolver desafíos complejos y eficientes."


# Universidades/instituciones, nombre y titulo/certificado
university:
- name: Universidad Mariano Gálvez
  pic: umg.png
  degree: Maestría en Seguridad Informática

- name: Universidad Mariano Gálvez
  pic: 1.jpg
  degree: Maestría en Seguridad Informática
  
- name: Universidad Mariano Gálvez
  pic: 2.jpg
  degree: Maestría en Seguridad Informática

- name: Universidad Mariano Gálvez
  pic: 3.jpg
  degree: Maestría en Seguridad Informática

- name: Universidad Mariano Gálvez
  pic: umg.png
  degree: Ingeniería en Sistemas de Información y Ciencias de la Computación

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty